// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDpYkzo0qlMYoQ2JYt0aYv7C8T2Asf1Xc',
    appId: '1:883994384562:web:88e3c4972c0b1b2b9751ab',
    messagingSenderId: '883994384562',
    projectId: 'beta-conquistando-4fb10',
    authDomain: 'beta-conquistando-4fb10.firebaseapp.com',
    storageBucket: 'beta-conquistando-4fb10.appspot.com',
    measurementId: 'G-DQH71LRDF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_TJW9gYM6l86ZiPhWkBH1g0EqW6sueYo',
    appId: '1:883994384562:android:91b581fc4d1fa9999751ab',
    messagingSenderId: '883994384562',
    projectId: 'beta-conquistando-4fb10',
    storageBucket: 'beta-conquistando-4fb10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLjmqgLo621NNjOqaUY80ZooLdNuNAOGc',
    appId: '1:883994384562:ios:ad0aef12e5d9d8419751ab',
    messagingSenderId: '883994384562',
    projectId: 'beta-conquistando-4fb10',
    storageBucket: 'beta-conquistando-4fb10.appspot.com',
    iosClientId: '883994384562-g815gsgafcnn3negbnpehv5p7egem0co.apps.googleusercontent.com',
    iosBundleId: 'com.example.conquistandoomundo',
  );
}
